-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 20:33:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veterinaria_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `veterinaria_db` ;

-- -----------------------------------------------------
-- Schema veterinaria_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veterinaria_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `veterinaria_db` ;

-- -----------------------------------------------------
-- Table `veterinaria_db`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`Rol` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`Rol` (
  `id_rol` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`Usuario` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(30) NULL,
  `id_rol` TINYINT UNSIGNED NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `veterinaria_db`.`Rol` (`id_rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`Cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `veterinaria_db`.`Usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`Mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`Mascota` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`Mascota` (
  `id_mascota` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `especie` VARCHAR(60) NOT NULL,
  `raza` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_mascota`),
  INDEX `idx_mascota_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_mascota_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `veterinaria_db`.`Cliente` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`TipoAtencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`TipoAtencion` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`TipoAtencion` (
  `id_tipo_atencion` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_atencion`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`EstadoTurno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`EstadoTurno` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`EstadoTurno` (
  `id_estado_turno` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_estado_turno`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`Especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`Especialidad` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`Especialidad` (
  `id_especialidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_especialidad`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`Veterinario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`Veterinario` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`Veterinario` (
  `id_veterinario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `matricula` VARCHAR(50) NOT NULL,
  `Especialidad_id_especialidad` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_veterinario`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `matricula` (`matricula` ASC) VISIBLE,
  INDEX `fk_Veterinario_Especialidad1_idx` (`Especialidad_id_especialidad` ASC) VISIBLE,
  CONSTRAINT `fk_veterinario_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `veterinaria_db`.`Usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Veterinario_Especialidad1`
    FOREIGN KEY (`Especialidad_id_especialidad`)
    REFERENCES `veterinaria_db`.`Especialidad` (`id_especialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`Turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`Turno` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`Turno` (
  `id_turno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_mascota` INT UNSIGNED NOT NULL,
  `id_veterinario` INT UNSIGNED NOT NULL,
  `id_usuario_creador` INT UNSIGNED NOT NULL,
  `id_estado_turno` TINYINT UNSIGNED NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `motivo` VARCHAR(500) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_turno`),
  INDEX `fk_turno_creador` (`id_usuario_creador` ASC) VISIBLE,
  INDEX `fk_turno_estado` (`id_estado_turno` ASC) VISIBLE,
  INDEX `idx_turno_fecha_estado` (`fecha_hora` ASC, `id_estado_turno` ASC) VISIBLE,
  INDEX `idx_turno_mascota` (`id_mascota` ASC) VISIBLE,
  INDEX `idx_turno_veterinario_fecha` (`id_veterinario` ASC, `fecha_hora` ASC) VISIBLE,
  CONSTRAINT `fk_turno_creador`
    FOREIGN KEY (`id_usuario_creador`)
    REFERENCES `veterinaria_db`.`Usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turno_estado`
    FOREIGN KEY (`id_estado_turno`)
    REFERENCES `veterinaria_db`.`EstadoTurno` (`id_estado_turno`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turno_mascota`
    FOREIGN KEY (`id_mascota`)
    REFERENCES `veterinaria_db`.`Mascota` (`id_mascota`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turno_veterinario`
    FOREIGN KEY (`id_veterinario`)
    REFERENCES `veterinaria_db`.`Veterinario` (`id_veterinario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`AtencionClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`AtencionClinica` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`AtencionClinica` (
  `id_atencion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_turno` INT UNSIGNED NULL DEFAULT NULL,
  `id_mascota` INT UNSIGNED NOT NULL,
  `id_veterinario` INT UNSIGNED NOT NULL,
  `id_tipo_atencion` TINYINT UNSIGNED NOT NULL,
  `diagnostico` TEXT NULL DEFAULT NULL,
  `tratamiento` TEXT NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `proximo_control` DATE NULL DEFAULT NULL,
  `fecha_atencion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_usuario_ultima_modificacion` INT UNSIGNED NULL DEFAULT NULL,
  `fecha_ultima_modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_atencion`),
  UNIQUE INDEX `id_turno` (`id_turno` ASC) VISIBLE,
  INDEX `fk_atencion_veterinario` (`id_veterinario` ASC) VISIBLE,
  INDEX `fk_atencion_tipo` (`id_tipo_atencion` ASC) VISIBLE,
  INDEX `fk_atencion_modificador` (`id_usuario_ultima_modificacion` ASC) VISIBLE,
  INDEX `idx_atencion_mascota_fecha` (`id_mascota` ASC, `fecha_atencion` ASC) VISIBLE,
  CONSTRAINT `fk_atencion_mascota`
    FOREIGN KEY (`id_mascota`)
    REFERENCES `veterinaria_db`.`Mascota` (`id_mascota`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atencion_modificador`
    FOREIGN KEY (`id_usuario_ultima_modificacion`)
    REFERENCES `veterinaria_db`.`Usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atencion_tipo`
    FOREIGN KEY (`id_tipo_atencion`)
    REFERENCES `veterinaria_db`.`TipoAtencion` (`id_tipo_atencion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atencion_turno`
    FOREIGN KEY (`id_turno`)
    REFERENCES `veterinaria_db`.`Turno` (`id_turno`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atencion_veterinario`
    FOREIGN KEY (`id_veterinario`)
    REFERENCES `veterinaria_db`.`Veterinario` (`id_veterinario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`HorarioAtencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`HorarioAtencion` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`HorarioAtencion` (
  `id_horario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_veterinario` INT UNSIGNED NOT NULL,
  `dia_semana` TINYINT UNSIGNED NOT NULL COMMENT '1=lunes ... 7=domingo',
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `intervalo_minutos` SMALLINT UNSIGNED NOT NULL DEFAULT '30',
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `HorarioAtencioncol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_horario`),
  INDEX `idx_horario_veterinario_dia` (`id_veterinario` ASC, `dia_semana` ASC) VISIBLE,
  CONSTRAINT `fk_horario_veterinario`
    FOREIGN KEY (`id_veterinario`)
    REFERENCES `veterinaria_db`.`Veterinario` (`id_veterinario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `veterinaria_db`.`VacunaAplicada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veterinaria_db`.`VacunaAplicada` ;

CREATE TABLE IF NOT EXISTS `veterinaria_db`.`VacunaAplicada` (
  `id_vacuna_aplicada` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_vacuna` VARCHAR(120) NOT NULL,
  `dosis` VARCHAR(80) NULL DEFAULT NULL,
  `lote` VARCHAR(80) NULL DEFAULT NULL,
  `fecha_aplicacion` DATE NOT NULL,
  `proxima_aplicacion` DATE NULL DEFAULT NULL,
  `laboratorio` VARCHAR(120) NULL DEFAULT NULL,
  `AtencionClinica_id_atencion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_vacuna_aplicada`),
  INDEX `fk_VacunaAplicada_AtencionClinica1_idx` (`AtencionClinica_id_atencion` ASC) VISIBLE,
  CONSTRAINT `fk_VacunaAplicada_AtencionClinica1`
    FOREIGN KEY (`AtencionClinica_id_atencion`)
    REFERENCES `veterinaria_db`.`AtencionClinica` (`id_atencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
